services:
  client:
    container_name: "birthday-notifier__client"
    build:
      context: "./client"
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/client
      - /app/client/node_modules/
    environment:
      REACT_APP_GOOGLE_API_CLIENT_ID: "${GOOGLE_OAUTH_CLIENT_ID}"
      REACT_APP_GOOGLE_OAUTH_REDIRECT_URI: "${GOOGLE_OAUTH_REDIRECT_URI}"
  api:
    container_name: "birthday-notifier__api"
    build:
      context: "./api"
    depends_on:
      - migrations
    ports:
      - "3001:3001"
    volumes:
      - ./:/app/api
    environment:
      API_PORT: "${API_PORT}"
      GOOGLE_OAUTH_CLIENT_ID: "${GOOGLE_OAUTH_CLIENT_ID}"
      GOOGLE_OAUTH_CLIENT_SECRET: "${GOOGLE_OAUTH_CLIENT_SECRET}"
  migrations:
    container_name: "birthday-notifier__migrations"
    build:
      context: "./db"
    depends_on:
      - db
    volumes:
      - ./:/app/migrations
    environment:
      FLYWAY_LOCATIONS: "filesystem:./sql"
      FLYWAY_URL: "${FLYWAY_URL}"
      FLYWAY_USER: "${POSTGRES_USER}"
      FLYWAY_PASSWORD: "${POSTGRES_PASSWORD}"
  db:
    container_name: "birthday-notifier__db"
    image: postgres:13.2
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
